//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspose.CreateProjectWizard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspose.CreateProjectWizard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon aspose {
            get {
                object obj = ResourceManager.GetObject("aspose", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print barcode labels
        ///Generate barcode images and save to stream or image file
        ///Recognize barcodes from stream or image file
        ///Enhance your application workflow by adding barcode                   functionality
        ///Embed barcodes in documents to aid tracability
        ///Use the recognition functions to drive your real-life work                 processes
        ///Add barcode recognition to promote 3rd party services,                  for example send users to Amazon from the scanning of a              book barcode.
        /// </summary>
        internal static string Aspose_BarCode {
            get {
                return ResourceManager.GetString("Aspose.BarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel reporting - build dynamic Excel reports on the fly
        ///Create Excel dashboards, incorporating charts and pivot                tables
        ///High-fidelity Excel rendering and printing
        ///Import data from Excel spreadsheets
        ///Export data to Excel spreadsheets
        ///Spreadsheet generation
        ///Spreadsheet visualization through an Excel enabled grid for           both desktop and web
        ///Spreadsheet manipulation/editing
        ///Spreadsheet conversion.
        /// </summary>
        internal static string Aspose_Cells {
            get {
                return ResourceManager.GetString("Aspose.Cells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read multiple Visio formats including VSD, VSS, VST, VSX,          VTX,VDW and VDX
        ///Read properties of different objects in your diagram
        ///Save your diagrams as XML (VDX, VSX and VTX)
        ///Export your diagrams to images
        ///Export your diagrams to PDF
        ///Export your diagrams to XPS
        ///Export your diagram to HTML
        ///Export your diagram to SVG
        ///Export your diagram to SWF
        ///Read/change MS Visio document properties
        ///Print Visio diagrams with high fidelity
        ///Print Visio diagram on a server via XpsPrint API.
        /// </summary>
        internal static string Aspose_Diagram {
            get {
                return ResourceManager.GetString("Aspose.Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easily send email with HTML formatting and attachments
        ///Mail merge and send mass mail functions.
        ///Connect to POP3 and IMAP mail servers, list and download          messages locally.
        ///Connect to Microsoft Exchange Servers, list, download and          send messages.
        ///Create and update tasks using iCalendar.
        ///Load messages from file or stream (EML, MSG or MHT                   formats).
        ///Save messages to file or stream (EML, MSG or MHT formats).
        ///File format conversion (EML, MSG or MHT formats).
        ///Generate date [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Aspose_Email {
            get {
                return ResourceManager.GetString("Aspose.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create images from scratch
        ///Load and edit existing images
        ///Export images to a variety of formats
        ///Draw images using basic functionality like manipulating the            pixel information
        ///Draw images using advanced features like Graphics and              GraphicsPath.
        /// </summary>
        internal static string Aspose_Imaging {
            get {
                return ResourceManager.GetString("Aspose.Imaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read OneNote documents.
        ///Read properties of different objects in OneNote documents            (image, page).
        ///Save your OneNote document as image (PNG, BMP, GIF              and JPEG).
        ///Extract images from a OneNote document.
        ///Export OneNote documents to PDF.
        ///Extract text from OneNote document.
        ///Get information of each page from a OneNote document..
        /// </summary>
        internal static string Aspose_Note {
            get {
                return ResourceManager.GetString("Aspose.Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read text from images
        ///Read font and style information
        ///Extract text from whole image or a part of the image.
        /// </summary>
        internal static string Aspose_OCR {
            get {
                return ResourceManager.GetString("Aspose.OCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new PDF documents using product API.
        ///Transform XML and XSL-FO document into PDF
        ///Convert SVG files into PDF format
        ///Convert an image file into PDF format
        ///Convert an HTML page into PDF format
        ///Add tables and graph objects during PDF generation
        ///Add/update/delete text and images from PDF documents
        ///Insert, extract, append, concatenate PDF documents
        ///Split PDF document into single page documents
        ///Add headers and footers during PDF generation
        ///Add headings and table of contents during PDF creation.
        /// </summary>
        internal static string Aspose_Pdf {
            get {
                return ResourceManager.GetString("Aspose.Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new slides or clone existing slides from templates
        ///Create shapes on slides
        ///Add text to shapes
        ///Handle text and shape formatting
        ///Apply or remove protection on shapes
        ///Scan text from presentations
        ///Render slides to images
        ///Export presentations to PDF
        ///Add images to presentations
        ///Embed Excel charts as OLE objects in slides
        ///Generate presentations from database.
        /// </summary>
        internal static string Aspose_Slides {
            get {
                return ResourceManager.GetString("Aspose.Slides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new project files from scratch
        ///Define weekdays for the calendar
        ///Define exceptions in calendars
        ///Manage task baselines, costs and milestones
        ///Handle resource attributes
        ///Define resource assignment and allocation
        ///Render work breakdown structures (WBS) to images
        ///Render project data to HTML
        ///Sort tasks on names
        ///Sort resources on names
        ///Update custom properties of MPP Project files and write                 them back to original MPP format.
        /// </summary>
        internal static string Aspose_Tasks {
            get {
                return ResourceManager.GetString("Aspose.Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform mail merge
        ///Add barcodes to your Word documents
        ///Generate reports using mail merge
        ///Insert formatted text, paragraphs, images, tables and                     other content into a Word document
        ///Populate a table in a Word document using data retrieved            from a database
        ///Create mailing labels
        ///Insert a diagram into a Word document
        ///Combining documents, moving sections between documents.
        ///Mail merge data from multiple tables, format date and numeric        fields
        ///Insert a watermark into a doc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Aspose_Words {
            get {
                return ResourceManager.GetString("Aspose.Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspose provides .NET, Java, SSRS, SharePoint and JasperReports components for managing file formats, including Word, Excel, PowerPoint, PDF, Project, Flash, InfoPath and Metafiles. Other data visualization and utility components for Barcode, Charting and Ad Hoc query building are also offered..
        /// </summary>
        internal static string AsposeGeneralDetails {
            get {
                return ResourceManager.GetString("AsposeGeneralDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Banner {
            get {
                object obj = ResourceManager.GetObject("Banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotNetNuke.
        /// </summary>
        internal static string SolutionTitleText {
            get {
                return ResourceManager.GetString("SolutionTitleText", resourceCulture);
            }
        }
    }
}
